### ISSUE TITLE
Add nested fields

### ISSUE THREAD

**Issue by Frankkkkk** [Frankkkkk/pykorm#16]
AnyISalIn's MR https://github.com/Frankkkkk/pykorm/pull/11 introduced nested fields. It wasn't merged in #13  because some tests didn't pass and the change would've been too big.

However the idea was really good and they should be inttroduced into pykorm

**Comment by AnyISalIn** [comment]
nested fields in very important, It can reduce code redundancy.

**Comment by Frankkkkk** [comment]
I know I'm asking a lot, but would it be possible for you to rebase from the master branch and re-introduce the nested fields funcionality ? That would be very useful

**Comment by AnyISalIn** [comment]
ok, I will submit a new PR

**Comment by Frankkkkk** [comment]
Closed by #17
